services:
  web:
    container_name: runners-list-api-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    env_file:
      - .env
    environment:
      - GOCOVERDIR=/app/coverage
    volumes:
      - .:/app
      - ./coverage:/app/coverage
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: runners-list-db-test
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db-test: