services:
  web:
    container_name: runners-list-api-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
  db:
    container_name: runners-list-db-prod
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-db-prod: